### ISSUE TITLE
Custom class unavailable for type validation with dry-validation

### ISSUE THREAD

**Issue by ZimbiX** [trailblazer/reform#397]
### Complete Description of Issue

A custom class should be able to be used with the `type?` predicate of dry-validation, e.g.:

``` ruby
required(:facing).value(type?: Direction)
```

I thought there was a problem with dry-validation, but as it turns out, the root issue lies with Reform: https://github.com/dry-rb/dry-validation/issues/230
### Steps to reproduce

Modified from: http://dry-rb.org/gems/dry-validation/basics/built-in-predicates/#types

``` ruby
require 'rspec'
require 'reform'
require 'reform/form/dry'
Reform::Form.send :feature, Reform::Form::Dry

class Direction
end

RSpec.describe "type?" do
  let(:schema) do
    Dry::Validation.Schema do
      required(:facing).value(type?: Direction)
    end
  end

  class Form < Reform::Form
    # ::Dry::Types.register_class Direction
    property :facing, virtual: true
    validation do
      required(:facing).filled(type?: Direction)
    end
  end

  let(:input_valid)   { {facing: Direction.new} }
  let(:input_invalid) { {facing: Object.new} }

  it "as regular ruby" do
    expect(input_valid[:facing].class).to eq Direction
    expect(input_invalid[:facing].class).to_not eq Direction
  end

  it "with dry-validation" do
    expect(schema.call(input_valid).success?).to eq true
    expect(schema.call(input_invalid).success?).to eq false
  end

  it "with reform" do
    expect(Form.new(0).validate(input_valid)).to eq true
    expect(Form.new(0).validate(input_invalid)).to eq false
  end
end
```
### Expected behavior

It should load and pass tests without the line:

``` ruby
::Dry::Types.register_class Direction
```

which is supposed be used only for classes that are actually dry types.
### Actual behavior

Throws an exception while loading Form class:

```
Nothing registered with the key "direction" (Dry::Container::Error)
```
### System configuration

**Reform version**: 2.2.1
### Full Backtrace of Exception (if any)

```
/home/brendan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-container-0.5.0/lib/dry/container/resolver.rb:22:in `block in call': Nothing registered with the key "direction" (Dry::Container::Error)
    from /home/brendan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-container-0.5.0/lib/dry/container/resolver.rb:21:in `fetch'
    from /home/brendan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-container-0.5.0/lib/dry/container/resolver.rb:21:in `call'
    from /home/brendan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-container-0.5.0/lib/dry/container/mixin.rb:108:in `resolve'
    from /home/brendan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-container-0.5.0/lib/dry/container/mixin.rb:121:in `[]'
    from /home/brendan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-types-0.8.1/lib/dry/types.rb:67:in `block in []'
    from /home/brendan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.2/lib/concurrent/map.rb:133:in `block in fetch_or_store'
    from /home/brendan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.2/lib/concurrent/map.rb:122:in `fetch'
    from /home/brendan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.2/lib/concurrent/map.rb:132:in `fetch_or_store'
    from /home/brendan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-types-0.8.1/lib/dry/types.rb:58:in `[]'
    from /home/brendan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-types-0.8.1/lib/dry/types/compiler.rb:30:in `visit_type'
    from /home/brendan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-types-0.8.1/lib/dry/types/compiler.rb:15:in `visit'
    from /home/brendan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-types-0.8.1/lib/dry/types/compiler.rb:75:in `visit_key'
    from /home/brendan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-types-0.8.1/lib/dry/types/compiler.rb:15:in `visit'
    from /home/brendan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-types-0.8.1/lib/dry/types/compiler.rb:80:in `block in merge_with'
    from /home/brendan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-types-0.8.1/lib/dry/types/compiler.rb:80:in `map'
    from /home/brendan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-types-0.8.1/lib/dry/types/compiler.rb:80:in `merge_with'
    from /home/brendan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-types-0.8.1/lib/dry/types/compiler.rb:58:in `visit_form_hash'
    from /home/brendan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-types-0.8.1/lib/dry/types/compiler.rb:28:in `visit_type'
    from /home/brendan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-types-0.8.1/lib/dry/types/compiler.rb:15:in `visit'
    from /home/brendan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-types-0.8.1/lib/dry/types/compiler.rb:11:in `call'
    from /home/brendan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-validation-0.9.5/lib/dry/validation/input_processor_compiler.rb:16:in `call'
    from /home/brendan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-validation-0.9.5/lib/dry/validation/schema/deprecated.rb:14:in `input_processor'
    from /home/brendan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-validation-0.9.5/lib/dry/validation/schema/class_interface.rb:170:in `default_options'
    from /home/brendan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-validation-0.9.5/lib/dry/validation/schema/class_interface.rb:34:in `new'
    from /home/brendan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-validation-0.9.5/lib/dry/validation.rb:44:in `Schema'
    from /home/brendan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-validation-0.9.5/lib/dry/validation.rb:49:in `Form'
    from /home/brendan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reform-2.2.1/lib/reform/form/dry.rb:48:in `initialize'
    from /home/brendan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reform-2.2.1/lib/reform/form/dry.rb:33:in `new'
    from /home/brendan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reform-2.2.1/lib/reform/form/dry.rb:33:in `instance_exec'
    from /home/brendan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reform-2.2.1/lib/reform/validation.rb:15:in `validation'
    from /home/brendan/Projects/reform-dry-v-type-bug/reform-dry-v-type-bug.rb:20:in `<class:Form>'
    from /home/brendan/Projects/reform-dry-v-type-bug/reform-dry-v-type-bug.rb:17:in `block in <top (required)>'
    from /home/brendan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/example_group.rb:385:in `module_exec'
    from /home/brendan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/example_group.rb:385:in `subclass'
    from /home/brendan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/example_group.rb:258:in `block in define_example_group_method'
    from /home/brendan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/dsl.rb:43:in `block in expose_example_group_alias'
    from /home/brendan/Projects/reform-dry-v-type-bug/reform-dry-v-type-bug.rb:10:in `<top (required)>'
    from /home/brendan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/configuration.rb:1435:in `load'
    from /home/brendan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
    from /home/brendan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/configuration.rb:1433:in `each'
    from /home/brendan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
    from /home/brendan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/runner.rb:100:in `setup'
    from /home/brendan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/runner.rb:86:in `run'
    from /home/brendan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/runner.rb:71:in `run'
    from /home/brendan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/runner.rb:45:in `invoke'
    from /home/brendan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/exe/rspec:4:in `<top (required)>'
    from /home/brendan/.rbenv/versions/2.3.1/bin/rspec:23:in `load'
    from /home/brendan/.rbenv/versions/2.3.1/bin/rspec:23:in `<main>'
```

**Comment by fran-worley** [comment]
@ZimbiX so I've added a spec for this in the new dry branch (will be released as 2.3.0) (https://github.com/apotonick/reform/pull/388/commits/bfcd349fa478181ff6740dfdf4aa46465de287f7) and I can't replicate your issue there. 

That leaves us with a few options as to what this could be:
1) An issue with master (very likely, hence the new branch)
2) I've not accurately reproduced your circumstances in my spec (very possible take a look at the commit)
3) There is something wrong with your code (unlikely if your code is as you've provided it)

I can confirm that this isn't a dry issue as I've run a few tests with dry itself and don't get any errors so you're in the right place!

**Comment by fran-worley** [comment]
@ZimbiX are you able to update me on my comment above? Otherwise I'll assume that this issue is resolved in master and close.

**Comment by ZimbiX** [comment]
@fran-worley Oh sorry, I thought this was resolved! I'll have a look when I have time at some point in the next few days.

**Comment by ZimbiX** [comment]
Apologies for taking this long to get back to you.

From my testing, the issue is still present in the latest gem release (2.2.4), but is fixed before you add the test (bfcd349), and remains fixed in master (74f2715).

https://github.com/ZimbiX/reform-issue-397

Do you close issues where the fix is done but unreleased?

**Comment by fran-worley** [comment]
This should have been released as part of 2.3.0.rc1

I usually close them once they are in master with a passing test because I know the issue is resolved and we don't remove tests without a good reason! Though in this case it doesn't matter it should be in the latest release.

**Comment by ZimbiX** [comment]
Fair enough then. Cheers :smile:
