### ISSUE TITLE
:skip_if with :populator results in nil collection items

### ISSUE THREAD

**Issue by lastobelus** [trailblazer/reform#434]
### Complete Description of Issue

When using `:skip_if` option with `:populator` on a collection, nil is added to the collection for items where `skip_if` is true when at least one *unskipped* item follows.

The populator is not called for the skipped items, but `validate` raises `NoMethodError: undefined method 'validate!' for nil:NilClass` after the `deserialize` call. If you inspect the collection after deserialize, it will have nil items where items should have been skipped.

### Steps to reproduce
This can be reproduced by changing the test in `test/skip_if_test.rb` to use populator:

```ruby
class SkipIfTest < BaseTest

  class AlbumForm < TestForm
    property :title

    property :hit, skip_if: lambda { |options| options[:fragment]["title"]=="" } do
      property :title
      validation do
        required(:title).filled
      end
    end

    collection :songs, skip_if: :skip_song?, populator: :populate_song do
      property :title
    end

    def skip_song?(options)
      options[:fragment]["title"].nil? || options[:fragment]["title"].empty?
    end

    def populate_song(fragment:, collection:, index:, **)
      # this is not actually necessary, the populator is not called when skip_if is true
      # if fragment["title"].nil? || fragment["title"].empty?
        # return skip!
      # end

      if item = collection[index]
        item
      else
        collection.insert(index, BaseTest::Song.new(fragment))
      end
    end

  end

  let (:hit) { Song.new }
  let (:album) { Album.new(nil, hit, [], nil) }

  # skips deserialization when not present.
  it do
    form = AlbumForm.new(Album.new(nil, nil, []))
    # error occurs only for skipped items followed by one or more unskipped items, so we have to change the order of the params
    form.validate("songs" => [{"title" => nil}, {"title" => "Waste Of Breath"}]).must_equal true
    form.songs.size.must_equal 1
    form.songs[0].title.must_equal "Waste Of Breath"
  end

end
```

### Expected behavior
Test should pass without error. Note that the original form definition (using `populate_with_empty`) **does** pass with the order switched so the skipped item is not last. The bug only occurs when using `populator`.

### Actual behavior
Test errors:
```
  1) Error:
SkipIfTest#test_0003_anonymous:
NoMethodError: undefined method `validate!' for nil:NilClass
```
### System configuration
**Reform version**: 2.3.0rc1

### Full Backtrace of Exception (if any)
```
github/reform/lib/reform/contract/validate.rb:30:in `block (2 levels) in validate_nested!'
gems/disposable-0.4.3/lib/disposable/twin/property_processor.rb:24:in `block in collection!'
gems/disposable-0.4.3/lib/disposable/twin/property_processor.rb:24:in `each'
gems/disposable-0.4.3/lib/disposable/twin/property_processor.rb:24:in `each_with_index'
gems/disposable-0.4.3/lib/disposable/twin/property_processor.rb:24:in `each'
gems/disposable-0.4.3/lib/disposable/twin/property_processor.rb:24:in `collect'
gems/disposable-0.4.3/lib/disposable/twin/property_processor.rb:24:in `collection!'
gems/disposable-0.4.3/lib/disposable/twin/property_processor.rb:16:in `call'
github/reform/lib/reform/contract/validate.rb:30:in `block in validate_nested!'
gems/disposable-0.4.3/lib/disposable/twin/definitions.rb:27:in `block in each'
gems/disposable-0.4.3/lib/disposable/twin/definitions.rb:27:in `each'
gems/disposable-0.4.3/lib/disposable/twin/definitions.rb:27:in `each'
github/reform/lib/reform/contract/validate.rb:28:in `validate_nested!'
github/reform/lib/reform/contract/validate.rb:16:in `validate!'
github/reform/lib/reform/contract/validate.rb:10:in `validate'
github/reform/lib/reform/form/validate.rb:23:in `validate'
test/skip_if_test.rb:62:in `block in <class:SkipIfTest>'
```

**Comment by lastobelus** [comment]
I'm rather desperate for a fix or workaround for this.

**Comment by lastobelus** [comment]
I found the workaround: override `deserialize`, and delete the skipped items from the params.

**Comment by apotonick** [comment]
Nasty! But actually, I don't think `:skip_if` and `:populator` should be used together? That's why you have the ability to `skip!` in a populator.

**Comment by lastobelus** [comment]
@apotononick: in the end I decided not to use skip_if and populator together, not for any philosophical reason but because it made it easier to redraw the form when validation failed.

However I am of the opinion that even if one is philosophically opposed to using skip_if & populator together that this bug should be fixed. The fact that if your unit test happens to test items skipped in the wrong place it will pass is really a trap for users of the library.

**Comment by apotonick** [comment]
Agreeing on fixing, however, an alternative could be to simply note this in the docs. I have some dramatic changes planned for Reform 3, where all the leaky abstractions and the some fuzzy API sections could be fixed by re-designing the API itself. 

Fact is that many people like huge parts of Reform, but are struggling with the concepts of (pre-)population, deserialization, and skipping (For example, I have seen people using `:skip_if` to deserialize fragments, etc.). This indicates to me that the API and our concepts need adjustments. Primarily, I want to *visibly* separate deserialization/population from validation. Internally, these are two entirely contained objects, already, BTW. Nevertheless, we should discuss thhis in a separate thread.

**Comment by svoop** [comment]
Similar problem here, however, using `skip!` in the populator instead of `:skip_if` and a populator doesn't do the trick.

### Before

```ruby
collection :locations,
  form: LocationForm,
  populator: :populate_locations,
  skip_if: :skip_location?

def skip_location?(fragment:, **)
  fragment[:reference].blank?
end

def populate_locations(fragment:, collection:, index:, **)
  item = collection.find { |i| i.id.to_s == fragment['id'] }
  if fragment[:_destroy] == "1"
    collection.delete(item)
    return skip!
  end
  item ? item : collection.insert(index, Location.new)
end
```

This raises "undefined method `validate!' for nil:NilClass" here:
* https://github.com/trailblazer/reform/blob/v2.2.4/lib/reform/contract/validate.rb#L30
* https://github.com/apotonick/disposable/blob/v0.4.2/lib/disposable/twin/property_processor.rb#L24

### After

```ruby
collection :locations,
  form: LocationForm,
  populator: :populate_locations

def populate_locations(fragment:, collection:, index:, **)
  return skip! if fragment[:reference].blank?
  item = collection.find { |i| i.id.to_s == fragment['id'] }
  if fragment[:_destroy] == "1"
    collection.delete(item)
    return skip!
  end
  item ? item : collection.insert(index, Location.new)
end
```

This results in the same exception.

### Hack

Compacting the collection [here](https://github.com/apotonick/disposable/blob/v0.4.2/lib/disposable/twin/property_processor.rb#L24) helps.

```ruby
def collection!
  (@value || []).compact.each_with_index.collect { |nested_twin, i| yield(nested_twin, i) }
end
```

However, I'm not familiar enough with the inner workings of both reform and disposable to tell whether having `nil` in the collection serves a purpose in some situations.

**Comment by svoop** [comment]
@apotonick Maybe have a minute to look at my previous comment and judge whether I'm doing something wrong in my "After" example? Thanks a bunch!

**Comment by emaglio** [comment]
"Fixed" this raising an error if skip_if and populator are used together which is simply wrong.
We have a not for reform 3.0 to have a better solution than just raise an error

**Comment by svoop** [comment]
@emaglio The "fix" doesn't solve the problem me and others have when properly using `skip!` in the populator [as explained here](#issuecomment-307807763). The "undefined method `validate!' for nil:NilClass" is thrown whenever I delete an element from the collection by setting `_destroy` and add a new one. Any idea why? Worth spawning a new issue?

**Comment by emaglio** [comment]
@svoop did you remove `skip_if`?

**Comment by svoop** [comment]
@emaglio Yes, the exception happens with this setup:

```ruby
collection :locations,
  form: LocationForm,
  populator: :populate_locations

def populate_locations(fragment:, collection:, index:, **)
  return skip! if fragment[:reference].blank?
  item = collection.find { |i| i.id.to_s == fragment['id'] }
  if fragment[:_destroy] == "1"
    collection.delete(item)
    return skip!
  end
  item ? item : collection.insert(index, Location.new)
end
```
